---
title: "Tidyverse Cheat Sheet"
author: "Daniel Caley"
date: "4/23/2020"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r setup, message=FALSE, warning=FALSE}

library(tidyverse)
library(DT)

dt <- read_csv("rawData/CalculatedColumns_EmployeeData.csv")

```


# Pivoting Data
## Wide
 
```{r}

# Original Data set
us_rent_income %>% head() %>%  datatable(rownames = F)

# Pivot Wider Data Set
us_rent_income %>% 
  select(-moe) %>% pivot_wider(names_from = variable, values_from = estimate) %>% head() %>% datatable(rownames = F)

# Multiple Dimension Pivot Wider
us_rent_income %>%
  pivot_wider(names_from = variable, names_sep = "_", values_from = c(estimate, moe)) %>% head() %>%  datatable(rownames = F)

# Placing the seperator any where
us_rent_income %>%
  pivot_wider(
    names_from = variable,
    names_glue = "{variable}_{.value}",
    values_from = c(estimate, moe)
  ) %>% head() %>% datatable(rownames = F)


# Performing aggregations
warpbreaks <- as_tibble(warpbreaks[c("wool", "tension", "breaks")])
warpbreaks %>% datatable(rownames = F)

warpbreaks %>%
  pivot_wider(
    names_from = wool,
    values_from = breaks,
    values_fn = mean
  ) %>% datatable(rownames = F)

```


## Long

```{r}

relig_income %>% head() %>% datatable(rownames = F)

relig_income %>%
  pivot_longer(!religion, names_to = "income", values_to = "count") 


billboard %>% head() %>% datatable(rownames = F)

billboard %>%
 pivot_longer(
   cols = starts_with("wk"),
   names_to = "week",
   names_prefix = "wk",
   values_to = "rank",
   values_drop_na = TRUE
 ) %>% datatable(rownames = F)


# Multiple variables stored in column names
who %>% head() %>% datatable(rownames = F)

who %>% pivot_longer(
            cols = new_sp_m014:newrel_f65,
            names_to = c("diagnosis", "gender", "age"),
            names_pattern = "new_?(.*)_(.)(.*)",
            values_to = "count"
                      ) %>% head(500) %>% datatable(rownames = F)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}

covid <- read_csv("https://raw.githubusercontent.com/RamiKrispin/coronavirus/master/csv/coronavirus.csv")

covid <- covid  %>% 
  group_by(date, country, type) %>% 
  summarize(cases = sum(cases)) %>% 
  ungroup() %>% 
  mutate(is_china = if_else(country == "China","China","Not China"))

covid_wide <- covid %>% pivot_wider(names_from = type, values_from = cases) %>% filter(date >= "2020-04-01")

covid_wide_missing_dates <- covid %>% pivot_wider(names_from = type, values_from = cases) %>% 
                                      mutate(earth_population = 7800000000) %>% 
                                      filter(
                                              date >= "2020-04-01" & date <= "2020-04-10" | 
                                              date >= "2020-04-15" & date <= "2020-04-20" | date >= "2020-05-01" & date <= "2020-05-10"
                                              )

```


# Leveraging Across with rolling
More Info on [Across](https://www.tidyverse.org/blog/2020/04/dplyr-1-0-0-colwise/)
```{r}

#unloadNamespace("tsibble")
library(slider)
library(tsibble)


### Multiple Metrics by rolling 7 Days
covid_wide %>% group_by(country, is_china) %>% 
                  mutate(
                    across(c(confirmed, death), 
                           list(rolling = ~ slider::slide_dbl(., sum, .before = 6))
                           )
                    ) %>% 
                  mutate(across(contains("rolling"), list(growth = ~ . / lag(., 6) -1))) %>% 
                  head(5000) %>% datatable(rownames = F)

### Looking for complete rolling numbers

covid_wide %>% group_by(is_china) %>% 
                  mutate(
                    across(c(confirmed, death), 
                          list(rolling = ~ slider::slide_dbl(., sum, .before = 6, .complete = TRUE))),
                    across(contains("rolling"), list(growth = ~ . / lag(., 6) -1))
                  ) %>% head(5000) %>% datatable(rownames = F)

```

# Fill Gaps
https://www.rdocumentation.org/packages/tsibble/versions/0.9.3/topics/fill_gaps

```{r message=FALSE, warning=FALSE}

library(tsibble)

covid_wide_missing_dates %>% arrange(country, is_china) %>% 
                                  datatable(rownames = F)
                                  

# The fill function allows for the value previously to be populated.  If we didn't do that we would see NA.
covid_wide_missing_dates %>% as_tsibble(key = c(country, is_china), 
                                        index = date) %>% 
                             fill_gaps(confirmed = 0,
                                       death = 0) %>% 
                             group_by_key() %>% 
                             tidyr::fill(earth_population, 
                                         .direction = "down") %>% 
                             ungroup() %>% datatable(rownames = F)

```

# Wrangling Text
## Adding Text into SQL
```{r}

library(stringr)

bgn_date <- "2020-02-01"
end_date <- "2020-02-08"

sql <- str_glue("select customer_id, order_id, sales_price from orders where date_order between {bgn_date} and {end_date}")
sql

```

## Finding text in a string
```{r}

random_string <- "Dan is awesome!"
str_detect(random_string,"Dan")



```

## Extracting text in a string
```{r}


shopping_list <- c("apples x4", "bag of flour", "bag of sugar", "milk x2")
str_extract(shopping_list, "\\d") # Extracts number
str_extract(shopping_list, "[a-z]+") # Extracts characters
str_extract(shopping_list, "[a-z]{1,4}") # Extracts characters that are only 4 or less
str_extract(shopping_list, "\\b[a-z]{1,4}\\b")

```

## Replacing Text
```{r}

gsub("Dan","Daniel",random_string)

```

 
# Relocating or Moving Columns
```{r, message=FALSE, warning=FALSE}

# https://towardsdatascience.com/what-you-need-to-know-about-the-new-dplyr-1-0-0-7eaaaf6d78ac

### Moves the column to the far left
relocate_example <- mtcars %>% 
                    dplyr::relocate(disp) %>% 
                    head(3)

print(relocate_example)

# moves after a column
relocate_example2 <- mtcars %>% 
                      relocate(starts_with("c"), .after = disp)  %>% 
                      head(3)

print(relocate_example2)



```


# For Loops with if filter

```{r, message=FALSE, warning=FALSE}
this_is_a_list <- c(1,2,3,4,5)

for (l in this_is_a_list) {
  print(l)
  
}

for (l in this_is_a_list) {
  z <- if_else(l %% 2 == 0, "even","odd")
  print(paste0(as.character(l)," ",z))
}


```

